"""last update ts

Revision ID: 15b1d33fd8ac
Revises: a20ebbb175f2
Create Date: 2021-12-14 21:32:55.885212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15b1d33fd8ac'
down_revision = 'a20ebbb175f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('updated_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_datetime')
    # ### end Alembic commands ###
