"""added profile info

Revision ID: 16bc10e38889
Revises: c9edd8618bed
Create Date: 2021-12-03 21:29:20.924108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16bc10e38889'
down_revision = 'c9edd8618bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('world_part', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('acceptable_age_13_15', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('acceptable_age_15_18', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('acceptable_age_18_plus', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('birth_year', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('voice_chat', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('languages_speaking', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('languages_typing', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('scout', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('soldier', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('pyro', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('demoman', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('heavy', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('engineer', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('medic', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('sniper', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('spy', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('discord', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('about_me', sa.String(length=4096), nullable=True))
    op.add_column('user', sa.Column('active_coach', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'approved')
    op.drop_column('user', 'active_coach')
    op.drop_column('user', 'about_me')
    op.drop_column('user', 'discord')
    op.drop_column('user', 'spy')
    op.drop_column('user', 'sniper')
    op.drop_column('user', 'medic')
    op.drop_column('user', 'engineer')
    op.drop_column('user', 'heavy')
    op.drop_column('user', 'demoman')
    op.drop_column('user', 'pyro')
    op.drop_column('user', 'soldier')
    op.drop_column('user', 'scout')
    op.drop_column('user', 'languages_typing')
    op.drop_column('user', 'languages_speaking')
    op.drop_column('user', 'voice_chat')
    op.drop_column('user', 'birth_year')
    op.drop_column('user', 'acceptable_age_18_plus')
    op.drop_column('user', 'acceptable_age_15_18')
    op.drop_column('user', 'acceptable_age_13_15')
    op.drop_column('user', 'world_part')
    # ### end Alembic commands ###
