"""initial migration

Revision ID: 2a650d3f816d
Revises: 
Create Date: 2021-10-29 22:19:23.111116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a650d3f816d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steamid', sa.Integer(), nullable=True),
    sa.Column('created_ts', sa.DateTime(), nullable=True),
    sa.Column('is_coach', sa.Boolean(), nullable=True),
    sa.Column('nickname', sa.String(length=32), nullable=True),
    sa.Column('avatar32', sa.String(length=128), nullable=True),
    sa.Column('avatar64', sa.String(length=128), nullable=True),
    sa.Column('avatar184', sa.String(length=128), nullable=True),
    sa.Column('profile_url', sa.String(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('steam_account_created_date', sa.DateTime(), nullable=True),
    sa.Column('steam_real_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
