"""init migrate retry

Revision ID: a20ebbb175f2
Revises: 
Create Date: 2021-12-07 18:12:40.138541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a20ebbb175f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steamid', sa.BigInteger(), nullable=True),
    sa.Column('created_ts', sa.DateTime(), nullable=True),
    sa.Column('is_mentor', sa.Boolean(), nullable=True),
    sa.Column('nickname', sa.String(length=32), nullable=True),
    sa.Column('avatar32', sa.String(length=128), nullable=True),
    sa.Column('avatar64', sa.String(length=128), nullable=True),
    sa.Column('avatar184', sa.String(length=128), nullable=True),
    sa.Column('profile_url', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('steam_account_created_date', sa.DateTime(), nullable=True),
    sa.Column('steam_real_name', sa.String(length=128), nullable=True),
    sa.Column('steam_status', sa.Integer(), nullable=True),
    sa.Column('world_part', sa.String(length=10), nullable=True),
    sa.Column('acceptable_age_13_15', sa.Boolean(), nullable=True),
    sa.Column('acceptable_age_15_18', sa.Boolean(), nullable=True),
    sa.Column('acceptable_age_18_plus', sa.Boolean(), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('voice_chat', sa.Boolean(), nullable=True),
    sa.Column('languages_speaking', sa.String(length=256), nullable=True),
    sa.Column('languages_typing', sa.String(length=256), nullable=True),
    sa.Column('scout', sa.Boolean(), nullable=True),
    sa.Column('soldier', sa.Boolean(), nullable=True),
    sa.Column('pyro', sa.Boolean(), nullable=True),
    sa.Column('demoman', sa.Boolean(), nullable=True),
    sa.Column('heavy', sa.Boolean(), nullable=True),
    sa.Column('engineer', sa.Boolean(), nullable=True),
    sa.Column('medic', sa.Boolean(), nullable=True),
    sa.Column('sniper', sa.Boolean(), nullable=True),
    sa.Column('spy', sa.Boolean(), nullable=True),
    sa.Column('discord', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=4096), nullable=True),
    sa.Column('active_coach', sa.Boolean(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
