"""competitive

Revision ID: bc327b63d88d
Revises: c9af147ff107
Create Date: 2022-01-28 20:38:58.560992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc327b63d88d'
down_revision = 'c9af147ff107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('competitive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'competitive')
    # ### end Alembic commands ###
