"""if online, last online now

Revision ID: c9af147ff107
Revises: c9f57766b45c
Create Date: 2022-01-27 19:54:46.144122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9af147ff107'
down_revision = 'c9f57766b45c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('steam_last_online_calculated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'steam_last_online_calculated')
    # ### end Alembic commands ###
