"""moving steam_last_online_ts from ts to bigint

Revision ID: c9f57766b45c
Revises: 15b1d33fd8ac
Create Date: 2022-01-17 21:46:35.463790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f57766b45c'
down_revision = '15b1d33fd8ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('steam_last_online_ts', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'steam_last_online_ts')
    # ### end Alembic commands ###
